Test (#4)
* addding dummy script

* Updating runner

* adding status cheque

---------

Co-authored-by: Roshan Kumar <roshan.kumar@Apollo-Roshan-Kumars-Mac.local>

diff --git a/.github/workflows/revert-deploy.yml b/.github/workflows/revert-deploy.yml
--- a/.github/workflows/revert-deploy.yml
+++ b/.github/workflows/revert-deploy.yml
@@ -31,7 +31,7 @@ concurrency:
   cancel-in-progress: false
 
 jobs:
-  lock-master:
+  lock-master-branch:
     runs-on: ubuntu-latest
       #- self-hosted
       #- general
@@ -41,13 +41,19 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          curl -X PUT \
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X PUT \
             -H "Authorization: Bearer $GITHUB_TOKEN" \
             -H "Accept: application/vnd.github+json" \
             https://api.github.com/repos/owner/repository/branches/master/protection \
             -d '{
               "lock_branch": true
-            }'
+            }')
+          if [[ $response -lt 200 || $response -ge 300 ]]; then
+            echo "Failed to lock master branch. HTTP Status: $response"
+            exit 1
+          else
+            echo "Master branch locked successfully. HTTP Status: $response"
+          fi
 
   abort-pending-deployment:
     runs-on: ubuntu-latest
@@ -73,7 +79,7 @@ jobs:
     steps:
       - name: Identify target SHA
         id: target_sha
-        run: ./identify_target_sha.sh
+        run: ./scripts/identify-target-sha.sh
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
